import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const generalSans = localFont({
	src: [
		{
			path: "../fonts/GeneralSans-Regular.otf",
			weight: "400",
			style: "normal",
		},
		{
			path: "../fonts/GeneralSans-Italic.otf",
			weight: "400",
			style: "italic",
		},
		{
			path: "../fonts/GeneralSans-Bold.otf",
			weight: "700",
			style: "normal",
		},
		{
			path: "../fonts/GeneralSans-BoldItalic.otf",
			weight: "700",
			style: "italic",
		},
		{
			path: "../fonts/GeneralSans-Light.otf",
			weight: "300",
			style: "normal",
		},
		{
			path: "../fonts/GeneralSans-LightItalic.otf",
			weight: "300",
			style: "italic",
		},
		{
			path: "../fonts/GeneralSans-Semibold.otf",
			weight: "600",
			style: "normal",
		},
		{
			path: "../fonts/GeneralSans-SemiboldItalic.otf",
			weight: "600",
			style: "italic",
		},
		{
			path: "../fonts/GeneralSans-Extralight.otf",
			weight: "200",
			style: "normal",
		},
		{
			path: "../fonts/GeneralSans-ExtralightItalic.otf",
			weight: "200",
			style: "italic",
		},
		{
			path: "../fonts/GeneralSans-Medium.otf",
			weight: "500",
			style: "normal",
		},
		{
			path: "../fonts/GeneralSans-MediumItalic.otf",
			weight: "500",
			style: "italic",
		},
	],
	variable: "--font-generalSans",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={generalSans.variable}>
			<body>{children}</body>
		</html>
	);
}
